name: Develop to Staging Merge CI

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: technote-space/assign-author@v1.2.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Source Code
        uses: actions/checkout@v2-beta
        with:
          ref: refs/heads/develop

      - name: Create Pull Request onto Staging
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"                     # If blank, default: triggered branch
          destination_branch: "staging"          # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into Staging from Develop"
          pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
          pr_label: "auto-pr"                   # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}
